if(CMAKE_CROSSCOMPILING)
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
else()
  set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
endif()

include(CheckCCompilerFlag)
function(try_append_cflag flags_var flag)
  string(MAKE_C_IDENTIFIER ${flag} result)
  string(TOUPPER ${result} result)
  set(result "C_SUPPORTS${result}")
  check_c_compiler_flag(${flag} ${result})
  if(${result})
    string(STRIP "${${flags_var}} ${flag}" ${flags_var})
    set(${flags_var} ${${flags_var}} PARENT_SCOPE)
  endif()
endfunction()

include(CheckCXXCompilerFlag)
function(try_append_cxxflag flags_var flag)
  string(MAKE_C_IDENTIFIER ${flag} result)
  string(TOUPPER ${result} result)
  set(result "CXX_SUPPORTS${result}")
  check_cxx_compiler_flag(${flag} ${result})
  if(${result})
    string(STRIP "${${flags_var}} ${flag}" ${flags_var})
    set(${flags_var} ${${flags_var}} PARENT_SCOPE)
  endif()
endfunction()
